# Generated by Django 3.2.5 on 2021-07-06 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 0, 29, 11, 542192)),
        ),
    ]
