# Generated by Django 3.2.5 on 2021-07-06 10:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locus', '0002_alter_track_expiry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='geohash_link',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='locus.geohash'),
        ),
        migrations.AlterField(
            model_name='track',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 0, 33, 34, 852507)),
        ),
    ]
