# Generated by Django 3.2.5 on 2021-07-11 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locus', '0004_auto_20210706_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 12, 0, 0, 16, 524766)),
        ),
    ]
