# Generated by Django 3.2.5 on 2021-07-19 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locus', '0005_alter_track_expiry_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 2, 32, 14, 243567)),
        ),
    ]
